version: "3.8"
services:
   list-sql-server:
     container_name:listSql
     restart: always
     ports:
        -"1433:1433"
     volumes:
        - sql_volume:/var/opt/mssql/data
     environment:
        - "ACCEPT_EULA=1"
        - "MSSQL_SA_PASSWORD=MyPass@word"
        - "MSSQL_PID=Developer"
        - "MSSQL_USER=SA"
   list-mongo-server:
     container_name:listMongo
     restart: always
     ports:
        -"27017:27017"
     volumes:
        - mongo_volume:/data/db
   list-api:
     image: listapi
     build:
        context:.
        dockerfile: Final Case/Dockerfile
volumes:
  sql_volume:
  mongo_volume:
